# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2022 Sascha Brawer <sascha@brawer.ch>
#
# Containerfile for building an OCI-compliant container image

FROM python:3.10-alpine

LABEL org.opencontainers.image.licenses=MIT

COPY scraper /brandy/scraper
WORKDIR /brandy
RUN python3 -m pip install -r scraper/requirements.txt
RUN python3 -m unittest scraper/*_test.py

CMD ["/bin/sh"]
