# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2022 Sascha Brawer <sascha@brawer.ch>
#
# Kubernetes persistent volume claim for webserver

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webserver-storage
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: do-block-storage
